DROP TRIGGER IF EXISTS bm25_sync ON passage;
DROP FUNCTION IF EXISTS bm25_sync();


DROP FUNCTION IF EXISTS BM25_Okapi_rank(STRING,INT);
DROP FUNCTION IF EXISTS BM25_Okapi_rank(STRING,INT,FLOAT,FLOAT);
DROP FUNCTION IF EXISTS BM25_Okapi_IDF(STRING[]);
DROP FUNCTION IF EXISTS BM25_candidates(STRING,INT);

DROP FUNCTION IF EXISTS extract_passage_terms(TSVECTOR);
DROP FUNCTION IF EXISTS extract_passage_terms_freq(TSVECTOR);
DROP FUNCTION IF EXISTS tsv_doclen(TSVECTOR);
